"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.
"""

import os
import importlib.util
from pathlib import Path
from datetime import timedelta
from urllib.parse import parse_qs, urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR.parent / '.env')


def env_bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, str(default)).strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name: str, default: str = '') -> list[str]:
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-dev-secret-key-with-32-plus-bytes',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)

DEFAULT_ALLOWED_HOSTS = '127.0.0.1,localhost,192.168.0.24,171.102.174.35,stream.meownews.online'
ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    os.getenv('ALLOWED_HOSTS', DEFAULT_ALLOWED_HOSTS),
)

CSRF_TRUSTED_ORIGINS = [
    "https://stream.meownews.online",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'apps.accounts.apps.AccountsConfig',
]

CHANNELS_ENABLED = env_bool('CHANNELS_ENABLED', True) and importlib.util.find_spec('channels') is not None
if CHANNELS_ENABLED:
    INSTALLED_APPS.append('channels')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


def build_database_config() -> dict[str, str | int | Path]:
    database_url = os.getenv('DATABASE_URL')
    if database_url:
        parsed = urlparse(database_url)
        if parsed.scheme in {'postgres', 'postgresql'}:
            params = parse_qs(parsed.query)
            return {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': parsed.path.lstrip('/'),
                'USER': parsed.username or '',
                'PASSWORD': parsed.password or '',
                'HOST': parsed.hostname or 'localhost',
                'PORT': parsed.port or 5432,
                'OPTIONS': {
                    key: value[0] for key, value in params.items() if value
                },
            }

    db_engine = os.getenv('DB_ENGINE', 'django.db.backends.sqlite3')
    if db_engine == 'django.db.backends.sqlite3':
        return {
            'ENGINE': db_engine,
            'NAME': BASE_DIR / os.getenv('DB_NAME', 'db.sqlite3'),
        }

    return {
        'ENGINE': db_engine,
        'NAME': os.getenv('DB_NAME', ''),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': int(os.getenv('DB_PORT', '5432')),
    }


# Database
DATABASES = {
    'default': build_database_config(),
}

REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')
if CHANNELS_ENABLED:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }
ANT_MEDIA_BASE_URL = os.getenv('ANT_MEDIA_BASE_URL', 'https://media.meownews.online').rstrip('/')
ANT_MEDIA_APP_NAME = os.getenv('ANT_MEDIA_APP_NAME', 'live')
ANT_MEDIA_RTMP_BASE = os.getenv('ANT_MEDIA_RTMP_BASE', 'rtmp://media.meownews.online/live').rstrip('/')
ANT_MEDIA_PLAYBACK_BASE = os.getenv('ANT_MEDIA_PLAYBACK_BASE', 'https://media.meownews.online/live/streams').rstrip('/')
ANT_MEDIA_PREVIEW_BASE = os.getenv('ANT_MEDIA_PREVIEW_BASE', '').rstrip('/')
ANT_MEDIA_APPLICATION = ANT_MEDIA_APP_NAME
ANT_MEDIA_REST_APP_NAME = os.getenv('ANT_MEDIA_REST_APP_NAME', ANT_MEDIA_APPLICATION)
ANT_MEDIA_SYNC_STATUS = env_bool('ANT_MEDIA_SYNC_STATUS', False)
LBRY_DAEMON_URL = os.getenv('LBRY_DAEMON_URL', '').strip()
LBRY_DAEMON_TIMEOUT = int(os.getenv('LBRY_DAEMON_TIMEOUT', '5'))
LBRY_PLATFORM_WALLET_ID = os.getenv('LBRY_PLATFORM_WALLET_ID', '').strip()
LBRY_PLATFORM_ACCOUNT_ID = os.getenv('LBRY_PLATFORM_ACCOUNT_ID', '').strip()
LBRY_PLATFORM_RECEIVE_ADDRESS = os.getenv('LBRY_PLATFORM_RECEIVE_ADDRESS', '').strip()
MEMBERSHIP_ORDER_EXPIRE_MINUTES = int(os.getenv('MEMBERSHIP_ORDER_EXPIRE_MINUTES', '30'))
PRODUCT_ORDER_EXPIRE_MINUTES = int(os.getenv('PRODUCT_ORDER_EXPIRE_MINUTES', '30'))
PRODUCT_PLATFORM_RECEIVE_ADDRESS = os.getenv('PRODUCT_PLATFORM_RECEIVE_ADDRESS', '').strip()
PRODUCT_WALLET_PAYMENT_TREAT_THB_LTT_AS_NATIVE = env_bool('PRODUCT_WALLET_PAYMENT_TREAT_THB_LTT_AS_NATIVE', False)
PAYMENT_QR_SIGNING_SECRET = os.getenv('PAYMENT_QR_SIGNING_SECRET', '').strip()
PRODUCT_AUTO_PAYOUT_ENABLED = env_bool('PRODUCT_AUTO_PAYOUT_ENABLED', False)
PRODUCT_PAYOUT_WALLET_ID = os.getenv('PRODUCT_PAYOUT_WALLET_ID', '').strip()
PRODUCT_PAYOUT_ACCOUNT_ID = os.getenv('PRODUCT_PAYOUT_ACCOUNT_ID', '').strip()
PRODUCT_PAYOUT_MIN_DELAY_HOURS = int(os.getenv('PRODUCT_PAYOUT_MIN_DELAY_HOURS', '0'))
LBC_MIN_CONFIRMATIONS = int(os.getenv('LBC_MIN_CONFIRMATIONS', '1'))
LBC_TX_PAGE_SIZE = int(os.getenv('LBC_TX_PAGE_SIZE', '50'))

CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', DEBUG)

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_MINUTES', '30'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_DAYS', '7'))),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

AUTH_USER_MODEL = 'accounts.User'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
