from django.urls import path

from apps.accounts.views import (
    LiveChatMessageListCreateAPIView,
    LiveChatMessageModerationAPIView,
    LivePaymentMethodManageDetailAPIView,
    LivePaymentMethodManageListCreateAPIView,
    LivePaymentMethodPublicListAPIView,
    LivePaymentOrderCreateAPIView,
    LivePaymentOrderDetailAPIView,
    LivePaymentOrderMarkPaidAPIView,
    LiveStreamProductManageDetailAPIView,
    LiveStreamProductManageListCreateAPIView,
    LiveStreamProductPublicListAPIView,
    LiveStreamPrepareAPIView,
    LiveStreamCreateAPIView,
    LiveStreamDetailAPIView,
    LiveStreamListAPIView,
    LiveStreamStatusDetailAPIView,
    LiveStreamStatusAPIView,
    LiveStreamUpdateAPIView,
)

urlpatterns = [
    path('', LiveStreamListAPIView.as_view(), name='live-stream-list'),
    path('create/', LiveStreamCreateAPIView.as_view(), name='live-stream-create'),
    path('<int:pk>/', LiveStreamDetailAPIView.as_view(), name='live-stream-detail'),
    path('<int:pk>/status/', LiveStreamStatusDetailAPIView.as_view(), name='live-stream-status'),
    path('<int:pk>/products/', LiveStreamProductPublicListAPIView.as_view(), name='live-stream-products-public'),
    path('<int:pk>/chat/messages/', LiveChatMessageListCreateAPIView.as_view(), name='live-chat-messages'),
    path('<int:pk>/chat/messages/<int:message_id>/pin/', LiveChatMessageModerationAPIView.as_view(), name='live-chat-message-pin'),
    path('<int:pk>/chat/messages/<int:message_id>/', LiveChatMessageModerationAPIView.as_view(), name='live-chat-message-delete'),
    path('<int:pk>/payment-methods/', LivePaymentMethodPublicListAPIView.as_view(), name='live-payment-methods-public'),
    path('<int:pk>/payments/orders/', LivePaymentOrderCreateAPIView.as_view(), name='live-payment-order-create'),
    path('<int:pk>/payments/orders/<int:order_id>/', LivePaymentOrderDetailAPIView.as_view(), name='live-payment-order-detail'),
    path(
        '<int:pk>/payments/orders/<int:order_id>/mark-paid/',
        LivePaymentOrderMarkPaidAPIView.as_view(),
        name='live-payment-order-mark-paid',
    ),
    path('<int:pk>/payment-methods/manage/', LivePaymentMethodManageListCreateAPIView.as_view(), name='live-payment-methods-manage'),
    path(
        '<int:pk>/payment-methods/manage/<int:pm_id>/',
        LivePaymentMethodManageDetailAPIView.as_view(),
        name='live-payment-methods-manage-detail',
    ),
    path('<int:pk>/products/manage/', LiveStreamProductManageListCreateAPIView.as_view(), name='live-stream-products-manage'),
    path(
        '<int:pk>/products/manage/<int:binding_id>/',
        LiveStreamProductManageDetailAPIView.as_view(),
        name='live-stream-products-manage-detail',
    ),
    path('<int:pk>/prepare/', LiveStreamPrepareAPIView.as_view(), name='live-stream-prepare'),
    path('<int:pk>/update/', LiveStreamUpdateAPIView.as_view(), name='live-stream-update'),
    path('<int:pk>/start/', LiveStreamStatusAPIView.as_view(new_status='live'), name='live-stream-start'),
    path('<int:pk>/end/', LiveStreamStatusAPIView.as_view(new_status='ended'), name='live-stream-end'),
]
