from django.urls import path

from apps.accounts.views import (
    AdminRefundRequestApproveAPIView,
    AdminRefundRequestListAPIView,
    AdminRefundRequestMarkRefundedAPIView,
    AdminRefundRequestRejectAPIView,
    AdminProductOrderMarkSettledAPIView,
    ProductOrderConfirmReceivedAPIView,
    ProductOrderDetailAPIView,
    ProductOrderListCreateAPIView,
    ProductOrderMarkPaidAPIView,
    ProductOrderTxHintAPIView,
    ProductRefundRequestListCreateAPIView,
    SellerPayoutAddressDetailAPIView,
    SellerPayoutAddressListCreateAPIView,
    SellerProductOrderDetailAPIView,
    SellerProductOrderListAPIView,
    SellerRefundRequestListAPIView,
    SellerProductOrderShipAPIView,
)

urlpatterns = [
    path('product-orders/', ProductOrderListCreateAPIView.as_view(), name='product-order-list-create'),
    path('product-orders/<str:order_no>/', ProductOrderDetailAPIView.as_view(), name='product-order-detail'),
    path('product-orders/<str:order_no>/tx-hint/', ProductOrderTxHintAPIView.as_view(), name='product-order-tx-hint'),
    path('product-orders/<str:order_no>/mark-paid/', ProductOrderMarkPaidAPIView.as_view(), name='product-order-mark-paid'),
    path('product-orders/<str:order_no>/confirm-received/', ProductOrderConfirmReceivedAPIView.as_view(), name='product-order-confirm-received'),
    path('product-orders/<str:order_no>/refund-requests/', ProductRefundRequestListCreateAPIView.as_view(), name='product-order-refund-requests'),
    path('seller/product-orders/', SellerProductOrderListAPIView.as_view(), name='seller-product-order-list'),
    path('seller/product-orders/<str:order_no>/', SellerProductOrderDetailAPIView.as_view(), name='seller-product-order-detail'),
    path('seller/product-orders/<str:order_no>/ship/', SellerProductOrderShipAPIView.as_view(), name='seller-product-order-ship'),
    path('seller/payout-addresses/', SellerPayoutAddressListCreateAPIView.as_view(), name='seller-payout-address-list-create'),
    path('seller/payout-addresses/<int:id>/', SellerPayoutAddressDetailAPIView.as_view(), name='seller-payout-address-detail'),
    path('seller/refund-requests/', SellerRefundRequestListAPIView.as_view(), name='seller-refund-request-list'),
    path('admin/product-orders/<str:order_no>/mark-settled/', AdminProductOrderMarkSettledAPIView.as_view(), name='admin-product-order-mark-settled'),
    path('admin/refund-requests/', AdminRefundRequestListAPIView.as_view(), name='admin-refund-request-list'),
    path('admin/refund-requests/<int:pk>/approve/', AdminRefundRequestApproveAPIView.as_view(), name='admin-refund-request-approve'),
    path('admin/refund-requests/<int:pk>/reject/', AdminRefundRequestRejectAPIView.as_view(), name='admin-refund-request-reject'),
    path('admin/refund-requests/<int:pk>/mark-refunded/', AdminRefundRequestMarkRefundedAPIView.as_view(), name='admin-refund-request-mark-refunded'),
]
