# Generated by Django 5.2.11 on 2026-04-01 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_livechatroom_livechatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("watch_qr", "Watch QR"),
                            ("pay_qr", "Pay QR"),
                            ("paid_program_qr", "Paid Programming QR"),
                            ("crypto_address", "Crypto Address"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "qr_image",
                    models.FileField(
                        blank=True, null=True, upload_to="live/payment_qr/"
                    ),
                ),
                ("qr_text", models.TextField(blank=True, null=True)),
                ("wallet_address", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="accounts.livestream",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-created_at", "-id"],
            },
        ),
    ]
