# Generated by Django 5.2.11 on 2026-04-08 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_paymentorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="client_request_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_orders_marked_paid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="paid_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddConstraint(
            model_name="paymentorder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_request_id", ""), _negated=True),
                fields=("user", "stream", "client_request_id"),
                name="unique_payment_order_request_id_per_user_stream",
            ),
        ),
    ]
