# Generated by Django 5.2.11 on 2026-04-20 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_billingplan_wallet_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("price_lbc", models.DecimalField(decimal_places=8, max_digits=18)),
                ("duration_days", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="actual_amount_lbc",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="confirmations",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="expected_amount_lbc",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="order_no",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="pay_to_address",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="plan_code_snapshot",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="plan_name_snapshot",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="target_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="target_type",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="txid",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("tip", "Tip"),
                    ("product", "Product"),
                    ("paid_program", "Paid Program"),
                    ("membership", "Membership"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("expired", "Expired"),
                    ("failed", "Failed"),
                    ("underpaid", "Underpaid"),
                    ("overpaid", "Overpaid"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="ChainReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("LBC", "LBC")], default="LBC", max_length=10
                    ),
                ),
                ("address", models.CharField(max_length=128)),
                ("txid", models.CharField(max_length=128)),
                ("vout", models.PositiveIntegerField(blank=True, null=True)),
                ("amount_lbc", models.DecimalField(decimal_places=8, max_digits=18)),
                ("block_height", models.PositiveBigIntegerField(blank=True, null=True)),
                ("confirmations", models.PositiveIntegerField(default=0)),
                ("seen_at", models.DateTimeField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("unmatched", "Unmatched"),
                            ("matched", "Matched"),
                            ("ignored", "Ignored"),
                        ],
                        default="unmatched",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "matched_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chain_receipts",
                        to="accounts.paymentorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-seen_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txid", models.CharField(max_length=128)),
                ("amount_lbc", models.DecimalField(decimal_places=8, max_digits=18)),
                ("confirmations", models.PositiveIntegerField(default=0)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("matched_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="accounts.paymentorder",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_payments",
                        to="accounts.chainreceipt",
                    ),
                ),
            ],
            options={
                "ordering": ["-matched_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="UserMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=24,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="accounts.membershipplan",
                    ),
                ),
                (
                    "source_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_memberships",
                        to="accounts.paymentorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-ends_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="WalletAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=128, unique=True)),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("membership", "Membership"),
                            ("tip", "Tip"),
                            ("deposit", "Deposit"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("assigned", "Assigned"),
                            ("retired", "Retired"),
                        ],
                        default="available",
                        max_length=24,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "assigned_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_wallet_addresses",
                        to="accounts.paymentorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="wallet_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_orders",
                to="accounts.walletaddress",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentorder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order_no", ""), _negated=True),
                fields=("order_no",),
                name="unique_payment_order_no_when_present",
            ),
        ),
        migrations.AddIndex(
            model_name="chainreceipt",
            index=models.Index(
                fields=["address", "seen_at"], name="chain_receipt_address_seen_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chainreceipt",
            index=models.Index(
                fields=["match_status", "seen_at"], name="chain_receipt_match_seen_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chainreceipt",
            constraint=models.UniqueConstraint(
                fields=("currency", "txid", "vout"), name="unique_chain_receipt_output"
            ),
        ),
        migrations.AddIndex(
            model_name="orderpayment",
            index=models.Index(
                fields=["order", "payment_status"],
                name="order_payment_order_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderpayment",
            index=models.Index(fields=["txid"], name="order_payment_txid_idx"),
        ),
        migrations.AddConstraint(
            model_name="orderpayment",
            constraint=models.UniqueConstraint(
                fields=("order", "receipt"), name="unique_order_receipt_payment"
            ),
        ),
        migrations.AddIndex(
            model_name="usermembership",
            index=models.Index(
                fields=["user", "status", "ends_at"],
                name="membership_user_status_end_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usermembership",
            index=models.Index(
                fields=["starts_at", "ends_at"], name="membership_valid_window_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="walletaddress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("assigned_order__isnull", False)),
                fields=("assigned_order",),
                name="unique_wallet_address_assigned_order",
            ),
        ),
    ]
