# Generated by Django 5.2.11 on 2026-04-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_membershipplan_paymentorder_actual_amount_lbc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="walletaddress",
            name="account_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="walletaddress",
            name="wallet_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
