# Generated by Django 5.2.11 on 2026-04-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_walletaddress_account_id_walletaddress_wallet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chainreceipt",
            name="wallet_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
