# Generated by Django 5.2.11 on 2026-04-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_chainreceipt_wallet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="linked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="linked_wallet_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="user",
            name="primary_user_address",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="user",
            name="wallet_link_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("linked", "Linked"),
                    ("unlinked", "Unlinked"),
                    ("pending", "Pending"),
                ],
                default="",
                max_length=24,
            ),
        ),
    ]
