# Generated by Django 5.2.11 on 2026-04-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_alter_chainreceipt_currency_productorder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productorder",
            name="cancel_reason",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="productorder",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productorder",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productorder",
            name="stock_locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productorder",
            name="stock_released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
