# Generated by Django 5.2.11 on 2026-04-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0032_productorder_cancel_reason_productorder_cancelled_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletaddress",
            name="usage_type",
            field=models.CharField(
                choices=[
                    ("membership", "Membership"),
                    ("product", "Product"),
                    ("tip", "Tip"),
                    ("deposit", "Deposit"),
                    ("general", "General"),
                ],
                default="general",
                max_length=24,
            ),
        ),
    ]
