# Generated by Django 5.2.11 on 2026-04-27 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_sellerpayout_failure_note_productrefundrequest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DramaSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("cover", models.FileField(blank=True, upload_to="dramas/covers/")),
                ("tags", models.JSONField(blank=True, default=list)),
                ("total_episodes", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("favorite_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drama_series",
                        to="accounts.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DramaEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("episode_no", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                (
                    "video_file",
                    models.FileField(blank=True, upload_to="dramas/videos/"),
                ),
                ("video_url", models.URLField(blank=True)),
                ("hls_url", models.URLField(blank=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("is_free", models.BooleanField(default=False)),
                (
                    "unlock_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("meow_points", "Meow Points"),
                            ("membership", "Membership"),
                            ("ad_reward", "Ad Reward"),
                        ],
                        default="meow_points",
                        max_length=20,
                    ),
                ),
                ("meow_points_price", models.PositiveIntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="accounts.dramaseries",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "episode_no", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("series", "episode_no"),
                        name="unique_drama_episode_no_per_series",
                    )
                ],
            },
        ),
    ]
