# Generated by Django 5.2.11 on 2026-04-28 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_dramafavorite_dramawatchprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeowPointPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("points_amount", models.PositiveIntegerField(default=0)),
                ("bonus_points", models.PositiveIntegerField(default=0)),
                ("price_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("price_currency", models.CharField(default="THB-LTT", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MeowPointLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("bonus", "Bonus"),
                            ("reward", "Reward"),
                            ("spend", "Spend"),
                            ("refund", "Refund"),
                            ("admin_adjust", "Admin Adjust"),
                        ],
                        max_length=24,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("balance_before", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("target_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meow_point_ledger_entries",
                        to="accounts.paymentorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meow_point_ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MeowPointWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField(default=0)),
                ("total_earned", models.PositiveIntegerField(default=0)),
                ("total_spent", models.PositiveIntegerField(default=0)),
                ("total_purchased", models.PositiveIntegerField(default=0)),
                ("total_bonus", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meow_point_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
