# Generated by Django 5.2.11 on 2026-04-28 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_meowpointpackage_meowpointledger_meowpointwallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("tip", "Tip"),
                    ("product", "Product"),
                    ("paid_program", "Paid Program"),
                    ("membership", "Membership"),
                    ("meow_points_recharge", "Meow Points Recharge"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="MeowPointPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_no", models.CharField(max_length=64, unique=True)),
                (
                    "package_code_snapshot",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "package_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("points_amount", models.PositiveIntegerField(default=0)),
                ("bonus_points", models.PositiveIntegerField(default=0)),
                ("total_points", models.PositiveIntegerField(default=0)),
                ("price_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("price_currency", models.CharField(default="THB-LTT", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("credited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to="accounts.meowpointpackage",
                    ),
                ),
                (
                    "payment_order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meow_point_purchase",
                        to="accounts.paymentorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meow_point_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
