# Generated by Django 5.2.11 on 2026-04-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_gift_gifttransaction_dramaunlock"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="access_type",
            field=models.CharField(
                choices=[("free", "Free"), ("membership", "Membership")],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="preview_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
