# Generated by Codex on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_manualmembershippayment_status_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='status',
            field=models.CharField(
                choices=[
                    ('idle', 'Idle'),
                    ('ready', 'Ready'),
                    ('live', 'Live'),
                    ('ended', 'Ended'),
                ],
                default='idle',
                max_length=20,
            ),
        ),
    ]
