# Generated by Codex on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_livestream_status_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='ant_media_no_signal_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
