# Generated by Codex on 2026-05-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_videoshare_video_share_count_gifttransaction_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='order_type',
            field=models.CharField(
                choices=[
                    ('tip', 'Tip'),
                    ('product', 'Product'),
                    ('paid_program', 'Paid Program'),
                    ('membership', 'Membership'),
                    ('meow_points_recharge', 'Meow Points Recharge'),
                    ('meow_credits_recharge', 'Meow Credits Recharge'),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name='MeowCreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('credit_amount', models.PositiveIntegerField(default=0)),
                ('bonus_credit', models.PositiveIntegerField(default=0)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(default='THB-LTT', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.CreateModel(
            name='MeowCreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('total_recharged', models.PositiveIntegerField(default=0)),
                ('total_spent', models.PositiveIntegerField(default=0)),
                ('total_redeemed', models.PositiveIntegerField(default=0)),
                ('total_adjusted', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meow_credit_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.CreateModel(
            name='MeowCreditRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=64, unique=True)),
                ('package_code_snapshot', models.CharField(blank=True, default='', max_length=64)),
                ('package_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('credit_amount', models.PositiveIntegerField(default=0)),
                ('bonus_credit', models.PositiveIntegerField(default=0)),
                ('total_credit', models.PositiveIntegerField(default=0)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(default='THB-LTT', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('credited', 'Credited'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharges', to='accounts.meowcreditpackage')),
                ('payment_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meow_credit_recharge', to='accounts.paymentorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meow_credit_recharges', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='MeowCreditRedeemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeem_no', models.CharField(max_length=64, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('redeem_method', models.CharField(max_length=64)),
                ('account_snapshot', models.JSONField(default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_meow_credit_redeems', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meow_credit_redeem_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='MeowCreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('recharge', 'Recharge'), ('spend', 'Spend'), ('redeem', 'Redeem'), ('refund', 'Refund'), ('admin_adjust', 'Admin Adjust')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='completed', max_length=16)),
                ('amount', models.IntegerField()),
                ('balance_before', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meow_credit_ledger_entries', to='accounts.paymentorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meow_credit_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
