# Generated by Codex on 2026-05-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_meow_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=24)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, default='', max_length=8)),
                ('id_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driver_license', 'Driver License')], default='', max_length=32)),
                ('id_number', models.CharField(blank=True, default='', max_length=128)),
                ('id_expiry_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_front', 'ID Front'), ('selfie', 'Selfie')], max_length=24)),
                ('image', models.ImageField(upload_to='kyc/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.kycprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='kycdocument',
            constraint=models.UniqueConstraint(fields=('kyc_profile', 'document_type'), name='unique_kyc_document_type_per_profile'),
        ),
    ]
