# Generated by Codex on 2026-05-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dramaepisode',
            name='meow_credit_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dramaunlock',
            name='credit_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dramaunlock',
            name='credit_ledger_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drama_unlock', to='accounts.meowcreditledger'),
        ),
        migrations.AlterField(
            model_name='dramaunlock',
            name='source',
            field=models.CharField(choices=[('meow_points', 'Meow Points'), ('meow_credit', 'Meow Credit'), ('membership', 'Membership'), ('free', 'Free'), ('admin', 'Admin'), ('ad_reward', 'Ad Reward')], default='meow_points', max_length=24),
        ),
    ]
