# Generated by Codex on 2026-05-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_drama_interactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifttransaction',
            name='drama_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_transactions', to='accounts.dramaseries'),
        ),
    ]
