# Generated by Codex on 2026-05-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_gifttransaction_drama_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='dramaseries',
            name='gift_amount_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dramaseries',
            name='gift_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='credits_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='credit_ledger_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_transaction', to='accounts.meowcreditledger'),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='payment_method',
            field=models.CharField(choices=[('meow_points', 'Meow Points'), ('meow_credit', 'Meow Credit')], default='meow_points', max_length=24),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='points_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
