# Generated by Codex on 2026-05-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_drama_gift_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifttransaction',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='receiver_credit_ledger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_gift_transaction', to='accounts.meowcreditledger'),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='receiver_point_ledger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_gift_transaction', to='accounts.meowpointledger'),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='sender_credit_ledger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_gift_transaction', to='accounts.meowcreditledger'),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='sender_point_ledger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_gift_transaction', to='accounts.meowpointledger'),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='status',
            field=models.CharField(choices=[('succeeded', 'Succeeded'), ('refunded', 'Refunded'), ('reversed', 'Reversed')], default='succeeded', max_length=16),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='target_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='target_type',
            field=models.CharField(blank=True, choices=[('drama_series', 'Drama Series'), ('video', 'Video'), ('live_stream', 'Live Stream')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='meowcreditledger',
            name='entry_type',
            field=models.CharField(choices=[('recharge', 'Recharge'), ('spend', 'Spend'), ('redeem', 'Redeem'), ('refund', 'Refund'), ('admin_adjust', 'Admin Adjust'), ('gift_spend', 'Gift Spend'), ('gift_received', 'Gift Received')], max_length=24),
        ),
        migrations.AlterField(
            model_name='meowpointledger',
            name='entry_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('bonus', 'Bonus'), ('reward', 'Reward'), ('spend', 'Spend'), ('refund', 'Refund'), ('admin_adjust', 'Admin Adjust'), ('gift_spend', 'Gift Spend'), ('gift_received', 'Gift Received')], max_length=24),
        ),
    ]
