# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_gifttransaction_bilateral_ledgers'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='gift_amount_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='gift_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
